bicycle_model:
  length: 1.087
  width: 2.3
common:
  save_config: false
map:
  yaml_path: env/final_ver3/occupancy_grid_map.yaml
mpc:
  N: 20
  # Q:
  # - 1.1310615476533137
  # - 12.639788687906877
  # - 0.10323218808241448
  # QN:
  # - 21.48216822534218
  # - 240.06657063866555
  # - 1.9606813044415625
  # R:
  # - 1.0
  # - 0.011173925326603967

  Q:
  - 233.94231677015003
  - 697.757823829886
  - 0.17152200389177405
  QN:
  - 247.8745858030052
  - 739.3122969820384
  - 0.18173687538773567
  R:
  - 1.0
  - 0.016027363344058524
  a_max: 0.7
  a_min: -15.0
  accel_low_pass_gain: 1.0
  ay_max: 8.0
  control_rate: 40.0
  delta_max_deg: 32.0
  steer_low_pass_gain: 1.0
  steer_rate_max: 0.35
  steering_tire_angle_gain_var: 1.639
  use_max_kappa_pred: true
  v_max: 70.0
  wp_id_offset: 2
obstacles:
  csv_path: ''
  radius: 1.25
reference_path:
  circular: true
  csv_path: env/final_ver3/traj_mincurv.csv
  max_width: 6.0
  resolution: 0.6
  smoothing_distance: 2
  update_by_topic: false
  use_border_cells_topic: false
  use_path_constraints_topic: false
sim_logger:
  animation_enabled: false
v2x_obstacle_avoidance:
  position_jump_threshold: 5.0
  v_max_safety: 30.0
  vehicle_radius: 0.5
waypoints:
  csv_path: ''


frenet:
  enabled: true
  reprojection_rate_hz: 10
  lane_margin: 1.0
  lateral_offsets: [1.2, 1.5]
  T_overtake: [1.5,2.0,2.5,3.0]
  T_return: [1.5,2.0,2.5]
  clearance: 1.5
  ttc_thr: 1.5
  gap0: 2.0
  gap_t: 0.8